data_plotly.py, data_plotly_dialog.py, data_plotly_plot.py, ui/data_plotly_dialog_base.ui
This PR implements many different stuff:
* adds a method to call the DataPlotly dialog with a given dictionary, that is, allows the user to use DataPlotly API
* refactoring some code in `data_plotly_plot` by getting rid of some methods and refactoring the `data_ploty_dialog` to implement them
* adds the `Update Plot` button allowing the user to update the current plot (avoiding creating a new plot from scratch). If only a single plot is drawn, then the method works exactly as the `Create Plot` button, but if many plots are in the same canvas, it allows to update the last plot (only the last plot at the moment). It has been designed for a future standalone calling of DataPlotly giving the chance to update the plot with all the other customizations not available in the standalone …
=> Add standalone method and some code refactoring

processing/dataplotly_provider.py
There's no need for these settings outside of providers bundled
with the QGIS install which require external dependancies --
users can just deactive the whole plugin instead.
=> Remove setting to deactive processing provider

DataPlotly/processing/dataplotly_algorithms.py
Outputs are automatically created for FileDestination parameters
=> [processing] Avoid double-registering outputs (causes a startup warning)

DataPlotly/core/plot_types/box.py
fix #174 because if no X (optional) field is chosen an empty list is passed while we need a `None` value to correct render the plot
=> Fix boxplot if not X is set

DataPlotly/core/plot_factory.py
With new plotly version some API changed, one of them if the one to catch the selected bin ranges.
=> fix histogram selection

DataPlotly/core/plot_factory.py, DataPlotly/test/test_plot_factory.py
... so Plotly does not stumble over dates.  Fixes #122
Plotly uses its own JSON encoder, which currently cannot handle QDate or QDateTime objects. The JSON encoder [expects date objects to have an `isoformat` function](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/_plotly_utils/utils.py#L175) for converting dates to strings. This pull request adds such a function.
This approach avoids having to check and convert data types on the DataPlotly side.
=> Add "isoformat" function to QDate and QDateTime classes 

DataPlotly/core/plot_settings.py, DataPlotly/core/plot_types/bar_plot.py, DataPlotly/core/plot_types/scatter.py, DataPlotly/gui/plot_settings_widget.py, DataPlotly/processing/dataplotly_algorithms.py, DataPlotly/test/test_data_plotly_dialog.py, DataPlotly/test/test_qgis_environment.py, DataPlotly/ui/dataplotly_dockwidget_base.ui
A missing feature. The additional hover label can be set as *real* label to be shown ON the plot for both scatter and bar (other plots?).
**Scatter**
**Bar**
=> [Feature] additional labeling for scatter and bar plots

DataPlotly/core/plot_types/bar_plot.py
fixes #214 
we don't really need `ids` as a parameter, but it could become useful if we introduce animations. See https://plotly.com/python/reference/#bar-ids for a reference (each plot type has its own `ids`)
=> Fix wrong bar plot with categories

DataPlotly/gui/plot_settings_widget.py
Fixes #213 
This PR attempts to fix the following UI issues:
- After setting the properties in the widget, the whole widget is re-initialized, e.g. the combo box is cleared and the items are added again. Selected items like the marker type (points/lines/points+lines) are lost. I think removing the collapsedStateChanged event of the properties_group_box fixes this. I do not see a reason why we need this event.
- At widget initialization, I added the call to initialize the point and line combo boxes (refreshWidgets3 method) in order to hide the line combo box if the point marker is selected. Previously, refreshWidgets3() was only called after the marker type combo box changed.
- The in_color_combo data-defined-button had two problems. (1) It was not properly linked to the color combo box. …
=> Fix reinitializing properties widget

DataPlotly/gui/layout_item_gui.py
UX improvement in PlotLayoutItemWidget
Add double click event for plot list to show properties of selected plot
=> Double click plot in plot list to show properties

DataPlotly/core/plot_settings.py, DataPlotly/core/plot_types/plot_type.py, DataPlotly/gui/plot_settings_widget.py, DataPlotly/test/test_data_plotly_dialog.py, DataPlotly/ui/dataplotly_dockwidget_base.ui
Adds a `QgsColorButton` to the layout so that the user can choose the color of the gridaxis of the plot:
The color button allows to set also the opacity. Fully implemented also in the print layout.
fix #249
This PR could be also seen as a starting boilerplate for future layout customization.
@SGroe what do you think? @nyalldawson do you mind having a review :) ?
=> Allow to choose the gridaxis color of the plot

DataPlotly/layouts/plot_layout_item.py
Float now requires explicit cast to int
=> Fix TypeError with Python 3.10

DataPlotly/core/plot_expressions.py, DataPlotly/data_plotly.py
Adds a new custom function to the expression engine that can be used to get the colors of the category used. It works only for the `Categorized` renderer. 
@Gustry @nyalldawson can I have your bless here? :)
=> [feature] New custom function to get the colors from categories used

CHANGELOG.md
The tag this morning was 3.9.2
The bot didn't find the release content so it took the commit content
https://github.com/ghtmtt/DataPlotly/releases/tag/3.9.2
=> Fix correct version in the changelog

DataPlotly/gui/plot_settings_widget.py
Minimal improvment : finally I find a way to create plot when project is readed :)
We have to click on the button to create the plot. When project is cleared, the plot view is not cleared
No needs anymoreto click on the button to create the plot. When project is cleared, the plot view is  now cleared
=> Auto create clear plot

.github/workflows/test_plugin.yaml, CHANGELOG.md, DataPlotly/core/plot_types/bar_plot.py, DataPlotly/gui/plot_settings_widget.py, DataPlotly/metadata.txt
New option to set the bar width to automatically. Especially useful with time series where the bar width should be manually calculated to milliseconds. With the `Auto` option enabled, the plotly backend will take care of it
=> Fix bar width

CHANGELOG.md, DataPlotly/processing/dataplotly_provider.py
Fix to #331
Maybe a more visible warning will be better to invite users to install it. But at least, the plugin can load without a Python error
=> Fix loading of the plugin without panda installed

CHANGELOG.md, DataPlotly/gui/dock.py
To avoid the Python error with `qgis_process` : 
```bash
➜ qgis_process run native:atlaslayouttomultiplepdf --distance_units=meters --area_units=m2 --ellipsoid=NONE --project_path=/home/etienne/dev/python/lizmap-plugin/lizmap/test/data/lizmap_3_3.qgs --LAYOUT=landscape --COVERAGE_LAYER=/home/etienne/dev/python/lizmap-plugin/lizmap/test/data/lines.geojson --FILTER_EXPRESSION= --SORTBY_EXPRESSION= --SORTBY_REVERSE=false --FORCE_VECTOR=false --FORCE_RASTER=false --GEOREFERENCE=true --INCLUDE_METADATA=true --DISABLE_TILED=false --SIMPLIFY=true --TEXT_FORMAT=0 --IMAGE_COMPRESSION=0 --OUTPUT_FILENAME= --OUTPUT_FOLDER=/tmp/
Traceback (most recent call last):
File "/home/etienne/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/dock.py", line 131, in addDocksFromProject …
```
=> Do not add docks if self.iface is not defined when using qgis_process

DataPlotly/core/plot_factory.py, DataPlotly/core/plot_settings.py
Otherwise things get murky when we re-use the same settings objects with multiple factories, as the factory plot generation logic modifies settings (eg by recording the list of found feature ids)
Fixes incomplete plots when used with atlas
=> Deepcopy settings when creating factories

DataPlotly/metadata.txt
I'm starting updating some plugins about their URL (related to Lizmap BTW, in the latest release of server side)
* repository : The GIT repository
* tracker : the issue tracker
* homepage : the more UI friendly page for presenting the plugin, so I'm suggesting to redirect straight to the README.md ?
I'm agree, still not the best, but a little bit better ?
Do you have another link in mind or soon ? Github Pages with help ?
=> Update metadata.txt about homePage

DataPlotly/core/core_utils.py, DataPlotly/data_plotly.py, DataPlotly/gui/plot_settings_widget.py, DataPlotly/metadata.txt
Follow up from #367 from @visr and my previous PR #354
I didn't know about the online link.
=> Use the readthedocs link in the Help menu and in metadata.txt

DataPlotly/core/plot_types/plot_type.py
With plotly 6 installed and DataPlotly enabled, opening any QGIS project (without any plotting) raises a ValueError. In Plotly 6, passing a string to title and using titlefont on axes is no longer supported. Use title.text and title.font instead. The fixed version also works in Plotly 5, currently shipped with QGIS.
Related links to plotly:
https://github.com/plotly/plotly.py/releases/tag/v6.0.0rc0
https://github.com/plotly/plotly.js/pull/7212
Tested on Linux Mint 21.2 with the following setups:
- QGIS 3.42.1, Plotly 6.0.1
- QGIS 3.40.3, Plotly 5.4.0
**Traceback**
ValueError: Invalid property specified for object of type plotly.graph_objs.layout.XAxis: 'titlefont' Did you mean "tickfont"?
Traceback (most recent call last):
File "/home/riannek/.local/share/QGIS/QGIS3/profiles/default/python …
=> Fix ValueError with Plotly >= 6 by moving titlefont to title.font

DataPlotly/core/plot_factory.py
We use "get" to avoid key error when the settings are not in the dictionnary. For instance when the project was saved with an older version of dataplotly that didn't have the settings yet.
Funded by INRAE
=> fix issue 379

DataPlotly/core/plot_types/radar.py
Use the correct length for generating the color list so that each entity gets a unique color.
Previously, the number of colors was tied to the number of parameters, causing display issues.
Funded by INRAE
=> Fix issue 386
