- help/source/bar.rst
- help/source/basic_usage.rst
- help/source/box.rst
- help/source/from_console.rst
fixed typo errors in manual after translation
> fixed typos after translating into Dutch

- data_plotly.py
- processing/dataplotly_algorithms.py
- processing/dataplotly_provider.py
Use QGIS application method to register and unregister the processing provider
> Processing - Improve the loading of the algorithm provider

- i18n/DataPlotly_en.ts
- i18n/DataPlotly_es.ts
- i18n/DataPlotly_fr.ts
- i18n/DataPlotly_it.ts
- i18n/DataPlotly_nl.ts
- i18n/DataPlotly_sv.ts
fix typo cavas instead of canvas
> fix typo cavas instead of canvas

- data_plotly_dialog.py
- ui/dataplotly_dockwidget_base.ui
Minor UI tweaks to improve appearance and consistency of dock
> Unify dock appearance with layer styling dock

- data_plotly_dialog.py
- data_plotly_plot.py
Changed the default polar plot direction to clockwise and set x-values (independent variable) to display as r (angles) and y-values to display as theta (radial distance)
> Revise Polar Plot

- DataPlotly/data_plotly_dialog.py
- DataPlotly/data_plotly_plot.py
@nyalldawson a super small code fix discovered during Italian [QGIS SummerCamp](http://qgis.it/summer_camp.html)
> fix annoying bug with subplots in rows

- README.md
As the title explains, no other changes
> just add the Travis badge to the README

- DataPlotly/test/test_data_plotly_dialog.py
- DataPlotly/test/test_plot_settings.py
Testing to see if we have a fragile test...
> Brute force test

- DataPlotly/core/plot_settings.py
- DataPlotly/data_plotly.py
- DataPlotly/data_plotly_dialog.py
- DataPlotly/gui/dock.py
- DataPlotly/test/test_data_plotly_dialog.py
- DataPlotly/test/test_resources.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
(this is also needed for the print layout designer)
> Transform dock into a stackable widget, color buttons now open inline

- DataPlotly/gui/plot_settings_widget.py
> Update vector layer of data defined buttons after layer selection changes

- DataPlotly/gui/plot_settings_widget.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
Fixes some HIG violations, cleans up some widget behavior
> Widget tweaks

- DataPlotly/core/plot_settings.py
- DataPlotly/data_plotly.py
- DataPlotly/gui/dock.py
- DataPlotly/gui/layout_item_gui.py
- DataPlotly/gui/plot_settings_widget.py
- DataPlotly/test/test_plot_settings.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
> Restore plot settings when loading projects

- DataPlotly/core/plot_factory.py
- DataPlotly/core/plot_settings.py
- DataPlotly/core/plot_types/bar_plot.py
- DataPlotly/core/plot_types/polar.py
- DataPlotly/core/plot_types/scatter.py
- DataPlotly/core/plot_types/ternary.py
- DataPlotly/gui/layout_item_gui.py
- DataPlotly/gui/plot_settings_widget.py
- DataPlotly/layouts/plot_layout_item.py
- DataPlotly/test/test_data_plotly_dialog.py
- DataPlotly/test/test_plot_factory.py
- DataPlotly/test/test_plot_settings.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
And some other nice features and cleanups!
> Add options to filter plots by layout map visiblity, atlas intersections

- DataPlotly/core/plot_factory.py
- DataPlotly/gui/layout_item_gui.py
> Fix data defined expressions using source layer fields don't work in layout based plots

- DataPlotly/core/plot_factory.py
- DataPlotly/core/plot_settings.py
- DataPlotly/core/plot_types/bar_plot.py
- DataPlotly/core/plot_types/box.py
- DataPlotly/core/plot_types/histogram.py
- DataPlotly/core/plot_types/plot_type.py
- DataPlotly/core/plot_types/scatter.py
- DataPlotly/core/plot_types/ternary.py
- DataPlotly/core/plot_types/violin.py
- DataPlotly/gui/plot_settings_widget.py
- DataPlotly/test/test_data_plotly_dialog.py
- DataPlotly/test/test_plot_factory.py
- DataPlotly/test/test_plot_settings.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
> Data defined layout

- DataPlotly/core/plot_settings.py
- DataPlotly/core/plot_types/violin.py
- DataPlotly/gui/plot_settings_widget.py
- DataPlotly/test/test_data_plotly_dialog.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
> [feature] show boxplot within violins

- DataPlotly/processing/dataplotly_algorithms.py
- DataPlotly/test/test_qgis_environment.py
Disable a test that is failing due to Proj 6 and just change the import of the Processing algorithm
> Fix test and Processing import

- DataPlotly/core/plot_types/plot_type.py
- DataPlotly/layouts/plot_layout_item.py
> Make layout plot backgrounds transparent

- publiccode.yml
Hi @ghtmtt,
this PR fixes some issues found by the publiccode.yml validator. 
In order to validate your publiccode.yml file, you can take a look at [this repository](https://github.com/italia/publiccode-parser-go) listing the possible ways to run the process. Futhermore, you could also insert the validation in your CI chain.
Let me know if you need further support.
Thanks!
> Fix some issues in the publiccode.yml file

- DataPlotly/ui/dataplotly_dockwidget_base.ui
> enable bins box when checkbox is checked fix #269

- DataPlotly/processing/dataplotly_algorithms.py
> Fix "Build a generic plot" processing algorithm

- DataPlotly/core/plot_factory.py
Just removing some deprecated notes in the IDE
I'm not sure about the version running in the package. @ghtmtt Are we fine with version numbers ?
> Update some deprecated notices about subplots

- DataPlotly/layouts/plot_layout_item.py
> fix stacktrace when removing all the plots in the print layout

- DataPlotly/gui/plot_settings_widget.py
The vector layer of all the data defined buttons are automatically set when the plot combo index changes
> fix signal when changing the plot index combobox

- .github/workflows/test_plugin.yaml
let's keep the docker updated with 3.22 and 3.28
> Update QGIS release in docker

- DataPlotly/core/plot_settings.py
- DataPlotly/core/plot_types/pie.py
- DataPlotly/gui/plot_settings_widget.py
- DataPlotly/ui/dataplotly_dockwidget_base.ui
#231
I've just add a spinbox with None when it's zero.
> feat: add hole option to pie chart

- DataPlotly/core/plot_types/pie.py
> fix : #324  key error pie_hole

- DataPlotly/core/plot_types/pie.py
@ghtmtt this should really fix the issue #324
> fix:  really fix this time #324

- DataPlotly/gui/plot_settings_widget.py
superseeds old https://github.com/ghtmtt/DataPlotly/pull/228
all credits to @jdugge
> Fix "type object 'DataType'
